pid_param:
  roll:
    pid_p: 3      #P
    pid_i: 0.1   #I
    pid_d: 0	    #D
    max_out: 1		#输出最大值的绝对值
    max_sum: 0.5  #累积误差最大值的绝对值
  pitch:
    pid_p: 10      #P
    pid_i: 0.1   #I
    pid_d: 0	    #D
    max_out: 1		#输出最大值的绝对值
    max_sum: 0.5  #累积误差最大值的绝对值
  yaw:
    pid_p: 1      #P
    pid_i: 0.0    #I
    pid_d: 0	    #D
    max_out: 1		#输出最大值的绝对值
    max_sum: 0.5  #累积误差最大值的绝对值
  velx:
    pid_p: 3      #P
    pid_i: 0.1   #I
    pid_d: 0	    #D
    max_out: 1		#输出最大值的绝对值
    max_sum: 0.5  #累积误差最大值的绝对值
  vely:
    pid_p: 3      #P
    pid_i: 0.10    #I
    pid_d: 0	    #D
    max_out: 1		#输出最大值的绝对值
    max_sum: 0.5  #累积误差最大值的绝对值
  velz:
    pid_p: 3      #P
    pid_i: 0.5    #I
    pid_d: 0	    #D
    max_out: 1		#输出最大值的绝对值
    max_sum: 0.5  #累积误差最大值的绝对值
