### controller config file ###
controller:
  ros__parameters:
    angle_pitch_integration_limit: 1.0 #俯仰角度积分限幅
    rate_pitch_integration_limit: 1.0 #俯仰角速率积分限幅 
    rate_yaw_integration_limit: 1.0 #艏向角速率积分限幅  
    vel_x_integration_limit: 1.0 #

    angle_pitch_output_limit: 1.0 #滚转角度PID输出限幅
    rate_pitch_output_limit: 1.0 #俯仰角速度PID输出限幅
    rate_yaw_output_limit: 1.0 #艏向角速度PID输出限幅 
    vel_x_output_limit: 1.0 
         
    dt: 0.05 #控制周期0.05S(20HZ)，非必要不修改

    angle_pitch_pid_P: 0.01 #pitch P
    angle_pitch_pid_I: 0.01 #pitch I
    angle_pitch_pid_D: 0.0 #pitch D        
    rate_pitch_pid_P: 1.0 #pitch rate P
    rate_pitch_pid_I: 0.0 #pitch rate I
    rate_pitch_pid_D: 0.0 #pitch rate D  
    
    rate_yaw_pid_P: 1.0 #航向角速度P
    rate_yaw_pid_I: 0.0 #航向角速度I
    rate_yaw_pid_D: 0.0 #航向角速度D    
    
    vel_x_pid_P: 1.5 #x轴速度P
    vel_x_pid_I: 0.0 #x轴速度I
    vel_x_pid_D: 0.01 #x轴速度D

    gs1_dir: -1   #舵机方向--水平1
    gs2_dir: 1    #舵机方向--水平2
    gs3_dir: 1    #舵机方向--垂直1
    gs4_dir: -1   #舵机方向--垂直2